"""
VibeSafe — CI/CD Integration

Provides GitHub Actions workflow scaffolding and CI mode support
for automated security scanning in pipelines.
"""

from __future__ import annotations

import os
from pathlib import Path

from rich.console import Console

console = Console()

GITHUB_ACTIONS_WORKFLOW = """\
# VibeSafe Security Scan — GitHub Actions Workflow
# Generated by: vibesafe ci-init
# Docs: https://github.com/cyberidfc9/Vibesafe

name: VibeSafe Security Scan

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]
  # Run weekly security scan
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  vibesafe-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install VibeSafe
        run: |
          pip install -e .
          # Optional: Install external security tools
          # pip install semgrep
          # See README for full tool installation guide

      # Optional: Install Gitleaks
      # - name: Install Gitleaks
      #   run: |
      #     curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
      #     chmod +x /usr/local/bin/gitleaks

      # Optional: Install Trivy
      # - name: Install Trivy
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'

      - name: Run VibeSafe Security Scan
        run: |
          vibesafe scan . --ci --format both
        env:
          CI: true

      - name: Upload Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vibesafe-security-report
          path: |
            vibesafe-report-*.html
            vibesafe-report-*.md
            vibesafe-report-*.pdf
          retention-days: 30

      # Optional: Comment on PR with results
      # - name: Comment PR
      #   if: github.event_name == 'pull_request'
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const fs = require('fs');
      #       const report = fs.readFileSync('vibesafe-report-*.md', 'utf8');
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: report.substring(0, 65000)
      #       });
"""


def scaffold_github_actions(project_path: str) -> str:
    """
    Create a GitHub Actions workflow file for VibeSafe CI/CD integration.

    Returns the path to the created workflow file.
    """
    workflows_dir = Path(project_path) / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)

    workflow_file = workflows_dir / "vibesafe-security.yml"

    if workflow_file.exists():
        console.print("  [yellow]⚠️  Workflow file already exists:[/yellow]")
        console.print(f"     {workflow_file}")
        console.print("  [dim]Use --force to overwrite.[/dim]")
        return str(workflow_file)

    workflow_file.write_text(GITHUB_ACTIONS_WORKFLOW, encoding="utf-8")
    return str(workflow_file)


def print_ci_init_success(workflow_path: str):
    """Print success message after CI init."""
    console.print()
    console.print("  [bold green]✅ GitHub Actions workflow created successfully![/bold green]")
    console.print()
    console.print(f"  📄 Workflow file: [cyan]{workflow_path}[/cyan]")
    console.print()
    console.print("  [bold]Next steps:[/bold]")
    console.print("  1. Commit the workflow file to your repository")
    console.print("  2. Push to trigger the first security scan")
    console.print("  3. View results in the Actions tab on GitHub")
    console.print()
    console.print("  [dim]Optional: Uncomment sections in the workflow to enable Gitleaks, Trivy, and PR commenting.[/dim]")
    console.print()


def get_ci_exit_code(scan_result, threshold: str = "high") -> int:
    """
    Determine CI exit code based on findings and threshold.

    Returns:
        0: No findings at or above threshold
        1: Findings found at or above threshold
    """
    from vibesafe.models import Severity

    threshold_map = {
        "critical": [Severity.CRITICAL],
        "high": [Severity.CRITICAL, Severity.HIGH],
        "medium": [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM],
        "low": [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW],
    }

    failing_severities = threshold_map.get(threshold.lower(), threshold_map["high"])

    for finding in scan_result.all_findings:
        if finding.severity in failing_severities:
            return 1

    return 0


def print_ci_summary(scan_result, threshold: str = "high"):
    """Print CI-friendly summary of scan results."""
    from vibesafe.models import Severity

    exit_code = get_ci_exit_code(scan_result, threshold)
    counts = scan_result.severity_counts

    console.print()
    console.print("  ╭─────────────────────────────────────╮")
    console.print("  │     🛡️  VibeSafe CI/CD Summary      │")
    console.print("  ╰─────────────────────────────────────╯")
    console.print()
    console.print(f"  Score: [bold]{scan_result.score}/100[/bold] ({scan_result.grade})")
    console.print(f"  Threshold: [bold]{threshold.upper()}[/bold]")
    console.print()
    console.print(f"  🔴 Critical: {counts.get(Severity.CRITICAL, 0)}")
    console.print(f"  🟠 High:     {counts.get(Severity.HIGH, 0)}")
    console.print(f"  🟡 Medium:   {counts.get(Severity.MEDIUM, 0)}")
    console.print(f"  🔵 Low:      {counts.get(Severity.LOW, 0)}")
    console.print(f"  ⚪ Info:     {counts.get(Severity.INFO, 0)}")
    console.print()

    if exit_code == 0:
        console.print("  [bold green]✅ PASSED — No findings at or above threshold[/bold green]")
    else:
        console.print("  [bold red]❌ FAILED — Findings exceed threshold[/bold red]")

    console.print()
    return exit_code
